"""
Phase: Final Synthesis.
Only runs after planning, retrieval, evidence extraction, and conflict
detection are complete -- the report is built FROM validated evidence,
not free-generated by the model.
"""
from app.ai.llm_client import get_llm_provider
from app.ai.output_parser import safe_parse_json
from app.ai.prompts import SYNTHESIS_SYSTEM, SYNTHESIS_PROMPT_TEMPLATE
from app.core.logging import get_logger

logger = get_logger(__name__)


async def synthesize_report(
    query: str,
    evidence_by_question_block: str,
    conflicts_block: str,
    sources_index_block: str,
) -> dict:
    provider = get_llm_provider()

    prompt = SYNTHESIS_PROMPT_TEMPLATE.format(
        query=query,
        evidence_by_question_block=evidence_by_question_block,
        conflicts_block=conflicts_block or "None detected.",
        sources_index_block=sources_index_block or "No sources retrieved.",
    )

    raw = await provider.generate_json(prompt, system=SYNTHESIS_SYSTEM, temperature=0.4)
    return safe_parse_json(raw)


def render_report_markdown(query: str, synthesis: dict) -> str:
    """Turns the structured synthesis JSON into the markdown shown in the UI."""
    lines = [f"# Research Report: {query}", ""]

    lines += ["## Executive Summary", synthesis.get("executive_summary", ""), ""]

    lines += ["## Key Findings"]
    for f in synthesis.get("key_findings", []):
        lines.append(f"- {f}")
    lines.append("")

    lines += ["## Opportunities"]
    for o in synthesis.get("opportunities", []):
        lines.append(f"- {o}")
    lines.append("")

    lines += ["## Risks"]
    for r in synthesis.get("risks", []):
        lines.append(f"- {r}")
    lines.append("")

    conflicts = synthesis.get("conflicting_evidence", [])
    if conflicts:
        lines += ["## Conflicting Evidence"]
        for c in conflicts:
            lines.append(f"- {c}")
        lines.append("")

    lines += ["## Recommendations"]
    for rec in synthesis.get("recommendations", []):
        indices = rec.get("supporting_source_indices", [])
        citation = " ".join(f"[Source {i}]" for i in indices)
        lines.append(f"- **{rec.get('recommendation', '')}** {citation}")
        lines.append(f"  - Why: {rec.get('why', '')}")
        lines.append(f"  - Confidence: {round(rec.get('confidence', 0) * 100)}%")
    lines.append("")

    lines += [f"**Overall confidence: {round(synthesis.get('overall_confidence', 0) * 100)}%**"]

    return "\n".join(lines)
